name: CI Workflow

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2

      - name: Cache Poetry virtual environment
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            venv-

      - name: Install Graphviz (dot)
        run: sudo apt-get install -y graphviz

      - name: Run make install
        run: make install

      - name: Run make format
        run: make format

      - name: Run make lint
        run: make lint

      - name: Run make type-check
        run: make type-check

      - name: Run make test
        run: make test

      - name: Run make build
        run: make build

      - name: Run make docker-build
        run: make docker-build
